# name: Upload
# on:
#   push:
# jobs:
#   Upload:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: npm
#           install-command: npm ci || npm install

#       - name: Create zip file
#         run: |
#           zip -r "$PROJECT_NAME.zip" *
#       - name: Submit extension
#         run: >
#           npx chrome-webstore-upload-cli@2 upload --extension-id $EXTENSION_ID
#           --client-id $CLIENT_ID --client-secret $CLIENT_SECRET --refresh-token
#           $REFRESH_TOKEN --zip-file "$PROJECT_NAME.zip"
#         env:
#           EXTENSION_ID: '${process.env.EXTENSION_ID}'
#           CLIENT_ID: '${process.env.CLIENT_ID}'
#           CLIENT_SECRET: '${process.env.CLIENT_SECRET}'
#           REFRESH_TOKEN: '${process.env.REFRESH_TOKEN}'
#       - name: Clean up
#         run: rm "$PROJECT_NAME.zip"
